### PR TITLE
8285497: Add system property for Java SE specification maintenance version

### PR DESCRIPTION
**Pull request by justin-curtis-lu**
Please review this PR which is a backport of adding the "java.specification.maintenance.version" system property.
The property is initialized with a value of 1, which corresponds with the Java SE 17 Maintenance Release 1.

Note that the only change in this backport is the uncommenting of the system property in `VersionProps.java.template`. And as such, the copyright year is updated to 2024, not the original backport year.

For reference, the approved CSR: https://bugs.openjdk.org/browse/JDK-8330418

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8330418](https://bugs.openjdk.org/browse/JDK-8330418) to be approved
- [x] [JDK-8285497](https://bugs.openjdk.org/browse/JDK-8285497) needs maintainer approval

### Issues
 * [JDK-8285497](https://bugs.openjdk.org/browse/JDK-8285497): Add system property for Java SE specification maintenance version (**Enhancement** - P4 - Approved)
 * [JDK-8330418](https://bugs.openjdk.org/browse/JDK-8330418): Add system property for Java SE specification maintenance version (**CSR**)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-ri.git pull/2/head:pull/2` \
`$ git checkout pull/2`

Update a local copy of the PR: \
`$ git checkout pull/2` \
`$ git pull https://git.openjdk.org/jdk17u-ri.git pull/2/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2`

View PR using the GUI difftool: \
`$ git pr show -t 2`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-ri/pull/2.diff">https://git.openjdk.org/jdk17u-ri/pull/2.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-ri/pull/2#issuecomment-2064328203)

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Changes match those already in 17, 11, and 8 to implement java.specification.maintenance.version.

**Review by prrace — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
Looks like a mostly clean backport of 8285497 with additional copyright header updates and the `java.specification.maintenance.version` commented out as needed.

**Pull request closed without merging**
