### PR TITLE
8331151: Update .jcheck/conf and version-numbers for 17.0.0.1

### PR DESCRIPTION
**Pull request by erikj79**
The version numbers defined in the source repository needs to be bumped for the new 17.0.0.1 release.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8331151](https://bugs.openjdk.org/browse/JDK-8331151) needs maintainer approval

### Issue
 * [JDK-8331151](https://bugs.openjdk.org/browse/JDK-8331151): Update .jcheck/conf and version-numbers for 17.0.0.1 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-ri.git pull/4/head:pull/4` \
`$ git checkout pull/4`

Update a local copy of the PR: \
`$ git checkout pull/4` \
`$ git pull https://git.openjdk.org/jdk17u-ri.git pull/4/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4`

View PR using the GUI difftool: \
`$ git pr show -t 4`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-ri/pull/4.diff">https://git.openjdk.org/jdk17u-ri/pull/4.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-ri/pull/4#issuecomment-2077860274)

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Verified date matches expected JCP Maintenance Release date.

**Review by prrace — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
Looks good.

**Comment by erikj79** [comment]
@gnu-andrew I'm adding the integrator config for the *-ri repos so for the rest of the PRs you can use the approve command.

**Pull request closed without merging**
