### PR TITLE
8307779: Relax the java.awt.Robot specification

### PR DESCRIPTION
**Pull request by azvegint**
Please review the doc only backport PR of https://github.com/openjdk/jdk/pull/13809.

It is clean backport of original commit + build failure fix.

CSR: [JDK-8330603](https://bugs.openjdk.org/browse/JDK-8330603)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change requires CSR request [JDK-8330603](https://bugs.openjdk.org/browse/JDK-8330603) to be approved
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8307779](https://bugs.openjdk.org/browse/JDK-8307779) needs maintainer approval

### Issues
 * [JDK-8307779](https://bugs.openjdk.org/browse/JDK-8307779): Relax the java.awt.Robot specification (**Bug** - P3 - Approved)
 * [JDK-8330603](https://bugs.openjdk.org/browse/JDK-8330603): Relax the java.awt.Robot specification (**CSR**)

### Reviewers
 * [Phil Race](https://openjdk.org/census#prr) (@prrace - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u-ri.git pull/3/head:pull/3` \
`$ git checkout pull/3`

Update a local copy of the PR: \
`$ git checkout pull/3` \
`$ git pull https://git.openjdk.org/jdk17u-ri.git pull/3/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3`

View PR using the GUI difftool: \
`$ git pr show -t 3`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u-ri/pull/3.diff">https://git.openjdk.org/jdk17u-ri/pull/3.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u-ri/pull/3#issuecomment-2065348341)

### CODE REVIEW

**Comment by azvegint** [comment]
/csr needed

https://bugs.openjdk.org/browse/JDK-8330603

**Comment by azvegint** [comment]
/issue add JDK-8308370

adding fix for the build failure

**Comment by azvegint** [comment]
/issue remove JDK-8308370

 [JDK-8308370](https://bugs.openjdk.org/browse/JDK-8308370): Fix build failures related to the java.awt.Robot documentation (Bug - P1) 
 
 changes included in this fix and the [CSR](https://bugs.openjdk.org/browse/JDK-8330603) updated accordingly

**Review by prrace — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Spec changes as expected for 17.0.0.1.

Associated CSR (JDK-8330603) already Approved.

**Review by gnu-andrew — APPROVED** [review]
Verified as a clean backport of 8307779 + 8308370
I don't know if it's worth mentioning 8308370 via `/issue`

**Pull request closed without merging**
